# Generated by Django 3.1.7 on 2021-08-12 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config_pannel', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='designated_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_componant_designate', to=settings.AUTH_USER_MODEL, verbose_name='Care Taker'),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='supply_belt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_component_belts', to='config_pannel.supplybelts'),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='water_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_component', to='config_pannel.waterscheme'),
        ),
    ]
