# Generated by Django 3.1.7 on 2021-08-20 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0002_waterscheme_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0005_remove_assetcomponent_water_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponentlog',
            name='labour_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcomponentlog',
            name='material_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcomponentlog',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assetcomponentlog',
            name='replacement_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_asset_component', to='maintenance.assetcomponentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_failure', models.CharField(blank=True, max_length=250, null=True)),
                ('maintenance_cost', models.FloatField()),
                ('maintenance_action', models.CharField(max_length=50)),
                ('interval', models.FloatField()),
                ('impact_of_failure', models.CharField(max_length=250)),
                ('possibility_of_failure', models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], max_length=50)),
                ('resulting_risk_score', models.FloatField()),
                ('mitigation', models.CharField(choices=[('Preventive', 'PREVENTIVE'), ('Inspection', 'INSPECTION'), ('Reactive', 'REACTIVE')], max_length=50)),
                ('next_action', models.DateField()),
                ('componant_picture', models.ImageField(blank=True, null=True, upload_to=maintenance.models.generate_path)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_info', to='maintenance.components')),
                ('designated_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_componant_designate', to=settings.AUTH_USER_MODEL, verbose_name='Care Taker')),
                ('supply_belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_component_belts', to='config_pannel.supplybelts')),
            ],
        ),
        migrations.AlterField(
            model_name='assetcomponentlog',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asset_component_log', to='maintenance.componentinfo'),
        ),
        migrations.DeleteModel(
            name='AssetComponent',
        ),
    ]
