# Generated by Django 3.1.7 on 2021-08-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20210820_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentinfo',
            old_name='interval',
            new_name='maintenance_interval',
        ),
    ]
