# Generated by Django 3.1.7 on 2021-08-20 08:46

from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0002_waterscheme_slug'),
        ('maintenance', '0007_auto_20210820_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('problem', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=250)),
                ('duration', models.IntegerField()),
                ('cost_total', models.FloatField()),
                ('labour_cost', models.FloatField(blank=True, null=True)),
                ('material_cost', models.FloatField(blank=True, null=True)),
                ('replacement_cost', models.FloatField(blank=True, null=True)),
                ('componant_picture', models.ImageField(blank=True, null=True, upload_to=maintenance.models.assetComponentLogFolder)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_component_log', to='maintenance.componentinfo')),
                ('supply_belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_comp_log', to='config_pannel.supplybelts')),
            ],
        ),
        migrations.DeleteModel(
            name='AssetComponentLog',
        ),
    ]
