# Generated by Django 3.1.7 on 2021-08-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_auto_20210820_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentinfolog',
            old_name='action',
            new_name='maintenance_action',
        ),
        migrations.RenameField(
            model_name='componentinfolog',
            old_name='problem',
            new_name='possible_failure',
        ),
        migrations.AlterField(
            model_name='componentinfo',
            name='next_action',
            field=models.DateField(blank=True, null=True),
        ),
    ]
