# Generated by Django 3.1.7 on 2021-08-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_auto_20210823_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfolog',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
    ]
