# Generated by Django 3.1.7 on 2021-08-30 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_auto_20210829_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
