# Generated by Django 3.1.7 on 2021-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_componentinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentinfo',
            name='designated_person',
        ),
        migrations.AddField(
            model_name='componentinfo',
            name='responsible',
            field=models.CharField(choices=[('Caretaker', 'CARETAKER'), ('Inspection', 'TECHNICIAN'), ('Other', 'OTHER')], default='Caretaker', max_length=50),
            preserve_default=False,
        ),
    ]
