# Generated by Django 3.1.7 on 2021-09-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_auto_20210905_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfo',
            name='impact_of_failure',
            field=models.CharField(choices=[('Total Loss Of Function', 'Total Loss Of Function'), ('Reduction of System Functionality', 'Reduction of System Functionality'), ('Reduction of Parts Functionality', 'Reduction of Parts Functionality'), ('Hardly any Effect', 'Hardly any Effect')], max_length=100),
        ),
        migrations.AlterField(
            model_name='componentinfo',
            name='possibility_of_failure',
            field=models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW'), ('Normal', 'NORMAl')], max_length=50),
        ),
    ]
