# Generated by Django 3.1.7 on 2021-09-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_componentinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfo',
            name='apply_date',
            field=models.DateField(default='2021-08-08'),
            preserve_default=False,
        ),
    ]
