# Generated by Django 3.1.7 on 2021-09-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_componentinfo_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfo',
            name='next_action_np',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='componentinfolog',
            name='maintenance_date_np',
            field=models.DateField(default='2078-5-20'),
            preserve_default=False,
        ),
    ]
