# Generated by Django 3.1.7 on 2021-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_auto_20210920_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfo',
            name='next_action_np',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='componentinfolog',
            name='maintenance_date_np',
            field=models.CharField(max_length=13),
        ),
    ]
