# Generated by Django 3.1.7 on 2021-10-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_componentinfo_componant_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentinfo',
            old_name='componant_numbers',
            new_name='component_numbers',
        ),
    ]
