# Generated by Django 3.1.7 on 2021-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_auto_20211003_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfo',
            name='next_action',
            field=models.DateField(blank=True, default='2021-10-04', null=True),
        ),
        migrations.AlterField(
            model_name='componentinfo',
            name='next_action_np',
            field=models.CharField(blank=True, default='2078-06-18', max_length=13, null=True),
        ),
    ]
