# Generated by Django 3.1.7 on 2021-11-01 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_auto_20211004_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_asset_component', to='maintenance.assetcomponentcategory'),
        ),
    ]
