# Generated by Django 3.1.7 on 2021-11-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_auto_20211101_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfo',
            name='mitigation',
            field=models.CharField(choices=[('Preventive', 'Preventive'), ('Inspection', 'Inspection'), ('Reactive', 'Reactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='componentinfo',
            name='possibility_of_failure',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Normal', 'Normal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='componentinfo',
            name='responsible',
            field=models.CharField(choices=[('Caretaker', 'Caretaker'), ('Technician', 'Technician'), ('Other', 'Other')], max_length=50),
        ),
    ]
