# Generated by Django 3.1.7 on 2021-11-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_auto_20211116_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfo',
            name='responsible',
            field=models.CharField(choices=[('Caretaker', 'Caretaker'), ('Technician', 'Technician'), ('Others', 'Others')], max_length=50),
        ),
    ]
