# Generated by Django 3.1.7 on 2021-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_auto_20211116_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfo',
            name='maintenance_action',
            field=models.CharField(max_length=250),
        ),
    ]
