# Generated by Django 3.1.7 on 2022-02-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0027_auto_20211125_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentinfo',
            name='supply_belt',
        ),
        migrations.RemoveField(
            model_name='componentinfolog',
            name='supply_belt',
        ),
    ]
