# Generated by Django 3.1.7 on 2022-02-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_auto_20220206_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfolog',
            name='log_type',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Issue', 'Issue')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentinfo',
            name='possibility_of_failure',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Minimal', 'Minimal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='componentinfo',
            name='responsible',
            field=models.CharField(max_length=50),
        ),
    ]
