# Generated by Django 3.1.7 on 2022-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0031_componentinfo_is_cost_seggregated'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfolog',
            name='is_cost_seggregated',
            field=models.BooleanField(default=False),
        ),
    ]
