# Generated by Django 3.1.7 on 2022-02-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0032_componentinfolog_is_cost_seggregated'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfo',
            name='interval_unit',
            field=models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], default='Year', max_length=30),
            preserve_default=False,
        ),
    ]
