# Generated by Django 3.1.7 on 2022-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0034_auto_20220511_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentinfolog',
            name='interval_unit',
        ),
        migrations.AlterField(
            model_name='componentinfolog',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
    ]
