# Generated by Django 3.1.7 on 2022-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0036_auto_20220511_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfolog',
            name='interval_unit',
            field=models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], default='Year', max_length=30),
        ),
    ]
