# Generated by Django 3.1.7 on 2022-05-19 10:41

from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0040_componentinfolog_log_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentInfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_image', models.ImageField(blank=True, null=True, upload_to=maintenance.models.assetComponentLogFolder)),
            ],
        ),
        migrations.AddField(
            model_name='componentinfolog',
            name='component_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maintenance.componentinfoimage'),
        ),
    ]
