# Generated by Django 3.1.7 on 2022-05-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0041_auto_20220519_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfoimage',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_component_image', to='maintenance.componentinfo'),
        ),
    ]
