# Generated by Django 3.1.7 on 2022-05-19 16:08

from django.db import migrations, models
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0044_componentinfologimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinfologimage',
            name='component_image',
            field=models.ImageField(blank=True, null=True, upload_to=maintenance.models.assetComponentLogImageFolder),
        ),
    ]
