# Generated by Django 3.1.7 on 2022-09-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0045_auto_20220519_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinfolog',
            name='component1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_component1', to='maintenance.components'),
        ),
        migrations.AlterField(
            model_name='componentinfolog',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_component_log', to='maintenance.componentinfo'),
        ),
    ]
