# Generated by Django 3.1.7 on 2021-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterscheme',
            name='slug',
            field=models.CharField(default='test', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
