# Generated by Django 3.1.7 on 2021-08-24 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0002_waterscheme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityTestParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('NDWQS_standard', models.CharField(blank=True, max_length=50, null=True)),
                ('water_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_test_parameter', to='config_pannel.waterscheme')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('supply_belts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_pannel.supplybelts')),
                ('water_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_test_results', to='config_pannel.waterscheme')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTestResultParamters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_parameters', to='config_pannel.qualitytestparameter')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='config_pannel.watertestresults')),
            ],
        ),
    ]
