# Generated by Django 3.1.7 on 2021-08-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0005_auto_20210825_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersupplyrecord',
            old_name='date_from',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='watersupplyrecord',
            name='date_to',
        ),
    ]
