# Generated by Django 3.1.7 on 2021-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0006_auto_20210825_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watersupplyrecord',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='watersupplyrecord',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
