# Generated by Django 3.1.7 on 2021-08-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0007_auto_20210825_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplyrecord',
            name='supply_date',
            field=models.DateField(default='2021-08-04'),
            preserve_default=False,
        ),
    ]
