# Generated by Django 3.1.7 on 2021-08-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0009_auto_20210825_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watersupplyrecord',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='watersupplyrecord',
            name='date_to',
        ),
    ]
