# Generated by Django 3.1.7 on 2021-08-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0010_auto_20210826_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watertestresults',
            old_name='date_from',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='watertestresults',
            name='date_to',
        ),
    ]
