# Generated by Django 3.1.7 on 2021-09-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0013_waterteriff_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpenseInflationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('dis_allow_edit', models.BooleanField(default=False)),
                ('water_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflation_parameter', to='config_pannel.waterscheme')),
            ],
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('yearly_expense', models.FloatField()),
                ('water_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_expense_scheme', to='config_pannel.waterscheme')),
            ],
        ),
    ]
