# Generated by Django 3.1.7 on 2021-09-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0014_otherexpense_otherexpenseinflationrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterscheme',
            name='beneficiary_household',
        ),
        migrations.RemoveField(
            model_name='waterscheme',
            name='beneficiary_population',
        ),
        migrations.RemoveField(
            model_name='waterscheme',
            name='institutional_connection',
        ),
        migrations.RemoveField(
            model_name='waterscheme',
            name='public_taps',
        ),
        migrations.CreateModel(
            name='WaterSchemeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_household', models.IntegerField(verbose_name='Number of Households')),
                ('beneficiary_population', models.IntegerField(verbose_name='Number of Benfficiary Population')),
                ('public_taps', models.IntegerField(verbose_name='Number of Public Taps')),
                ('institutional_connection', models.IntegerField()),
                ('apply_date', models.DateField()),
                ('water_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_scheme_data', to='config_pannel.waterscheme')),
            ],
        ),
    ]
