# Generated by Django 3.1.7 on 2021-09-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_auto_20210905_0833'),
        ('users', '0001_initial'),
        ('finance', '0008_auto_20210903_1050'),
        ('config_pannel', '0015_auto_20210903_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterterifflog',
            name='waterteriff_ptr',
        ),
        migrations.RenameField(
            model_name='waterteriff',
            old_name='rate',
            new_name='used_base_rate',
        ),
        migrations.DeleteModel(
            name='WaterSchemeLogTable',
        ),
        migrations.DeleteModel(
            name='WaterTeriffLog',
        ),
    ]
