# Generated by Django 3.1.7 on 2021-09-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0017_waterscheme_daily_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitytestparameter',
            name='types',
            field=models.CharField(choices=[('Chemical', 'CHEMICAL'), ('Other', 'OTHER')], default='Other', max_length=50),
        ),
    ]
