# Generated by Django 3.1.7 on 2021-09-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0019_auto_20210909_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseBasedUnitRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_from', models.IntegerField()),
                ('unit_to', models.IntegerField()),
                ('rate', models.FloatField()),
                ('estimated_paying_connection', models.FloatField()),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_based_units', to='config_pannel.waterteriff')),
            ],
        ),
    ]
