# Generated by Django 3.1.7 on 2021-09-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0021_waterteriff_apply_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterschemedata',
            name='apply_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
