# Generated by Django 3.1.7 on 2021-09-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0022_waterschemedata_apply_upto'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterscheme',
            name='monthly_account_mgmt',
            field=models.CharField(choices=[('en', 'ENGLISH-AD'), ('nep', 'NEPALI-BS')], default='nep', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterscheme',
            name='period',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterscheme',
            name='tool_start_date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='YearsInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_interval', to='config_pannel.waterscheme')),
            ],
            options={
                'verbose_name': 'MODELNAME',
                'verbose_name_plural': 'MODELNAMEs',
            },
        ),
    ]
