# Generated by Django 3.1.7 on 2021-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0025_auto_20210916_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterscheme',
            name='system_built_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterscheme',
            name='system_operation_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterscheme',
            name='system_operation_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
