# Generated by Django 3.1.7 on 2021-09-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0026_auto_20210916_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearsinterval',
            name='year_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
