# Generated by Django 3.1.7 on 2021-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0027_yearsinterval_year_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplyrecord',
            name='supply_date_np',
            field=models.CharField(default='2078-05-23', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watertestresults',
            name='date_np',
            field=models.CharField(default='2078-05-23', max_length=13),
            preserve_default=False,
        ),
    ]
