# Generated by Django 3.1.7 on 2021-09-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0028_auto_20210920_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watersupplyschedule',
            name='from_day',
        ),
        migrations.RemoveField(
            model_name='watersupplyschedule',
            name='to_day',
        ),
        migrations.AddField(
            model_name='watersupplyschedule',
            name='day',
            field=models.CharField(default='mon-saturday', max_length=40),
            preserve_default=False,
        ),
    ]
