# Generated by Django 3.1.7 on 2021-10-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0029_auto_20210924_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('income_notification_period', models.IntegerField(default=30)),
                ('expenditure_notification_period', models.IntegerField(default=30)),
                ('test_result_notification_period', models.IntegerField(default=30)),
                ('supply_record_notification_period', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Notification Period',
                'verbose_name_plural': 'Notification Periods',
            },
        ),
    ]
