# Generated by Django 3.1.7 on 2021-10-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0030_notificationperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationperiod',
            name='water_scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification_period', to='config_pannel.waterscheme'),
            preserve_default=False,
        ),
    ]
