# Generated by Django 3.1.7 on 2021-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0032_auto_20211002_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationperiod',
            name='last_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
