# Generated by Django 3.1.7 on 2021-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0033_notificationperiod_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationperiod',
            old_name='last_update',
            new_name='last_expense_push',
        ),
        migrations.AddField(
            model_name='notificationperiod',
            name='last_income_push',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationperiod',
            name='last_test_result_push',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationperiod',
            name='last_water_record_push',
            field=models.DateField(blank=True, null=True),
        ),
    ]
