# Generated by Django 3.1.7 on 2021-10-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0034_auto_20211022_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=250)),
                ('water_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_msg', to='config_pannel.waterscheme')),
            ],
        ),
    ]
