# Generated by Django 3.1.7 on 2021-11-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0037_notificationstore_title_np'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstore',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
