# Generated by Django 3.1.7 on 2021-11-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0038_auto_20211101_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterscheme',
            name='currency',
            field=models.CharField(default='Rs', max_length=20),
        ),
    ]
