# Generated by Django 3.1.7 on 2021-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0039_waterscheme_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='apply_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
