# Generated by Django 3.1.7 on 2021-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0040_otherexpense_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpense',
            name='apply_date',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
