# Generated by Django 3.1.7 on 2021-11-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0042_otherexpense_apply_upto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherexpense',
            options={'ordering': ['apply_date']},
        ),
        migrations.AlterModelOptions(
            name='waterschemedata',
            options={'ordering': ['apply_date']},
        ),
        migrations.AlterModelOptions(
            name='waterteriff',
            options={'ordering': ['apply_date']},
        ),
    ]
