# Generated by Django 3.1.7 on 2021-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0043_auto_20211125_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Expenditure', 'Expenditure')], default='Income', max_length=50),
            preserve_default=False,
        ),
    ]
