# Generated by Django 3.1.7 on 2021-11-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0044_otherexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpense',
            name='apply_upto',
            field=models.DateField(default='2021-05-02'),
            preserve_default=False,
        ),
    ]
