# Generated by Django 3.1.7 on 2021-11-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0046_auto_20211129_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherexpense',
            name='types',
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='apply_for_specific_date',
            field=models.BooleanField(default=False),
        ),
    ]
