# Generated by Django 3.1.7 on 2021-12-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0047_auto_20211129_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='one_time_cost',
            field=models.BooleanField(default=False),
        ),
    ]
