# Generated by Django 3.1.7 on 2021-12-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0048_otherexpense_one_time_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstore',
            name='notf_type',
            field=models.CharField(default='cashbook', max_length=50),
        ),
    ]
