# Generated by Django 3.1.7 on 2022-02-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0028_auto_20220206_0838'),
        ('config_pannel', '0049_notificationstore_notf_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterschemedata',
            name='beneficiary_population',
        ),
        migrations.RemoveField(
            model_name='watersupplyrecord',
            name='supply_belts',
        ),
        migrations.RemoveField(
            model_name='watersupplyschedule',
            name='supply_belts',
        ),
        migrations.RemoveField(
            model_name='watertestresults',
            name='supply_belts',
        ),
        migrations.DeleteModel(
            name='SupplyBelts',
        ),
    ]
