# Generated by Django 3.1.7 on 2022-02-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0050_auto_20220206_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterschemedata',
            old_name='public_taps',
            new_name='commercial_connection',
        ),
        migrations.RenameField(
            model_name='waterschemedata',
            old_name='beneficiary_household',
            new_name='household_connection',
        ),
        migrations.RenameField(
            model_name='watersupplyschedule',
            old_name='evening_from_time',
            new_name='time_from',
        ),
        migrations.RenameField(
            model_name='watersupplyschedule',
            old_name='evening_to_time',
            new_name='time_to',
        ),
        migrations.RemoveField(
            model_name='watersupplyrecord',
            name='estimated_beneficiaries',
        ),
        migrations.RemoveField(
            model_name='watersupplyrecord',
            name='estimated_household',
        ),
        migrations.RemoveField(
            model_name='watersupplyschedule',
            name='morning_from_time',
        ),
        migrations.RemoveField(
            model_name='watersupplyschedule',
            name='morning_to_time',
        ),
        migrations.AddField(
            model_name='waterschemedata',
            name='public_connection',
            field=models.IntegerField(default=1, verbose_name='Number of public Population'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterteriff',
            name='rate_for_commercial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterteriff',
            name='rate_for_public',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
