# Generated by Django 3.1.7 on 2022-02-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0051_auto_20220207_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterteriff',
            name='estimated_paying_connection_commercial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterteriff',
            name='estimated_paying_connection_public',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
