# Generated by Django 3.1.7 on 2022-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0052_auto_20220207_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterscheme',
            name='system_operation_from',
        ),
        migrations.RemoveField(
            model_name='waterscheme',
            name='system_operation_to',
        ),
        migrations.AddField(
            model_name='waterscheme',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterscheme',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
