# Generated by Django 3.1.7 on 2022-02-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0054_auto_20220215_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterscheme',
            name='water_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='WaterSource',
        ),
    ]
