# Generated by Django 3.1.7 on 2022-02-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0055_auto_20220215_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpenseinflationrate',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
