# Generated by Django 3.1.7 on 2022-05-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0056_auto_20220228_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='watersupplyschedule',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
