# Generated by Django 3.1.7 on 2022-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0057_watersupplyschedule_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitytestparameter',
            name='types',
            field=models.CharField(choices=[('Chemical', 'CHEMICAL'), ('Other', 'OTHER'), ('Physical', 'PHYSICAL')], default='Other', max_length=50),
        ),
    ]
