# Generated by Django 3.1.7 on 2022-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0058_auto_20220609_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitytestparameter',
            name='types',
            field=models.CharField(choices=[('Chemical', 'CHEMICAL'), ('Others', 'OTHERS'), ('Physical', 'PHYSICAL')], default='Other', max_length=50),
        ),
    ]
