# Generated by Django 3.1.7 on 2022-06-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0059_auto_20220610_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitytestparameter',
            name='types',
            field=models.CharField(choices=[('Chemical', 'CHEMICAL'), ('Others', 'OTHERS'), ('Physical', 'PHYSICAL')], default='Others', max_length=50),
        ),
    ]
