# Generated by Django 3.1.7 on 2022-09-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0060_auto_20220622_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertestresultparamters',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='config_pannel.qualitytestparameter'),
        ),
    ]
