# Generated by Django 3.1.7 on 2022-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_pannel', '0061_auto_20220925_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertestresultparamters',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
