# Generated by Django 3.1.7 on 2021-08-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closeincome',
            name='water_scheme',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CloseExpenditure',
        ),
        migrations.DeleteModel(
            name='CloseIncome',
        ),
    ]
