# Generated by Django 3.1.7 on 2021-08-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210813_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='date_np',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date_np',
            field=models.DateField(blank=True, null=True),
        ),
    ]
