# Generated by Django 3.1.7 on 2021-08-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210815_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='date_np',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_np',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
