# Generated by Django 3.1.7 on 2021-08-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20210824_0703'),
        ('finance', '0005_expenditure_maintenance_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='maintenance_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_log_expense', to='maintenance.componentinfolog'),
        ),
    ]
