# Generated by Django 3.1.7 on 2021-09-03 10:50

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_cashbookclosingmonth_cashbookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=finance.models.assetComponentLogFolder),
        ),
    ]
