# Generated by Django 3.1.7 on 2021-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20210903_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2021-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2021-01-01'),
            preserve_default=False,
        ),
    ]
