# Generated by Django 3.1.7 on 2021-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20211101_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='water_supplied',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
