# Generated by Django 3.1.7 on 2021-12-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0027_auto_20211125_1154'),
        ('finance', '0012_auto_20211118_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='maintenance_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_log_expense', to='maintenance.componentinfolog'),
        ),
    ]
