# Generated by Django 3.1.7 on 2022-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20211209_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='consumables_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='labour_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='replacement_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
