# Generated by Django 3.1.7 on 2021-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_lang',
            field=models.CharField(choices=[('en', 'en'), ('nep', 'nep')], default='en', max_length=5),
        ),
    ]
