# Generated by Django 3.1.7 on 2022-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220206_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='general_manager',
            field=models.BooleanField(default=False),
        ),
    ]
